on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'trigger workflow'
  push:
    branches:
      - main
      - release/*

jobs:
  install:
    runs-on: ubuntu-latest
    name: Install dependencies
    steps:
      - uses: actions/checkout@v2
      - name: yarn install
        uses: jaid/action-npm-install@v1.2.1
        with:
          packageManager: 'yarn'
  deploy:
    runs-on: ubuntu-latest
    name: Deploy API
    steps:
      - name: Deploy API
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: './packages/api'
